### ISSUE TITLE
Cannot Upload local asset files

### ISSUE THREAD

**Issue by surju87** [contentful/contentful.java#128]
Hi,

Q1. I'm looking for way to upload assets via java rest api's from local machine in contentful but didn't find anything. i can upload assets if it's in url form but not non-url.

Q2. Are you saving just url of assets which we are sending in request or downloading assets and saving it. i worried if you are storing just URL and what if assets get deleted from origin.

Q3. If my assets are stored at location where authentication is required before access them, then is there any way i can provide you "access-token/credentials" to contentful via java rest api.

Thanks
Santosh Kumar.

**Comment by surju87** [comment]
@mariobodemann if possible could you please respond..

**Comment by mariobodemann** [comment]
Hello,

sorry for the _long_ delay. 

1) Yes you are right: Right now we only accept urls to assets in order to upload them. No binary data, no files from your disk. You would need to use a third party upload and make it public accessable.
2) Once you [created an asset](http://docs.contentfulcma.apiary.io/#reference/assets/asset) and [processed](http://docs.contentfulcma.apiary.io/#reference/assets/asset-processing) it, waited for the succesfull processing, [publishing](http://docs.contentfulcma.apiary.io/#reference/assets/asset-publishing) it will make the asset available from our content delivery platform. I.e. you can delete the original url resource, since it got copied to our servers.
3) Short answer: No. We do have to get the asset from a public accessible url. If you find a 

All that said, there might be a solution in the works, but I cannot disclose any potentially existing timelines.

Greetings,
Mario

**Comment by surju87** [comment]
Thanks a lot @mariobodemann for your quick response.

**Comment by mariobodemann** [comment]
Also: Please be aware that this is the repository for the Content Delivery Api, so it is only there for delivering you the content you added through the UI, or the API. If you want to change contents on Contentful you would generally need to use the [Content Management API for Java](https://github.com/contentful/contentful-management.java ) repository, but please be aware that it has the same limitations as described above.
