### ISSUE TITLE
SDK is not honoring ETag responses

### ISSUE THREAD

**Issue by fcduarte** [contentful/contentful.java#171]
Hi team,

the SDK is not taking advantage of the ETag usage. Basically to automatically process ETags on `OkHttp` you need to create a cache in disk, more info here: https://android.jlelse.eu/reducing-your-networking-footprint-with-okhttp-etags-and-if-modified-since-b598b8dd81a1

`CDAClient` doesn't open access to its `OkHttpBuilder` making it impossible for calling `builder.cache()`. That way nothing will work.

Also, on the server side, Contentful is not implementing the spec correctly since it sends ETags back but without the `Cache-Control` header, making `OkHttp` not being able to figure out what to do with the response. More info here: https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching

This can be tagged as a feature request, allowing SDK clients to enable caching or as bug if you consider that the SDK is just ignoring the ETags and it shouldn't.

Let me know if any other information is required.

Best,

**Comment by fcduarte** [comment]
Hi Mario,

thanks for the quick response. After adding my own builder for OkHttp I start to see problems with the Bearer token:

````
Sending request https://preview.contentful.com/spaces/fyvbo1b1kt27/environments/master/locales on Connection{preview.contentful.com:443, proxy=DIRECT@ hostAddress=preview.contentful.com/54.210.156.163:443 cipherSuite=TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA protocol=http/1.1}
    Authorization: Bearer null
    User-Agent: contentful.java/10.0.0(Android Runtime 0.9) Linux/3.10.0+
    X-Contentful-User-Agent: sdk contentful.java/10.0.0; platform java/0.9.0; os Android/4.4.2;
    Host: preview.contentful.com
    Connection: Keep-Alive
    Accept-Encoding: gzip
````

Maybe the builder is replacing a default configuration from SDK?

Thanks!

**Comment by mariobodemann** [comment]
Hey,

hmm, that is odd. 

`setCallFactory` does replace the clients own builder, but you can request the clients `defaultCallFactoryBuilder()`, which will add the bearer token and the default configuration. You would use the default builder to add the needed cache, and then give the client builder the update okbuilder back, using the `setCallFactory`.

The crucial thing is to call the defaultCallFactoryBuilder after setting configurations on the client builder, so that the client builder has all configuration when creating the defaultCallFactoryBuilder.

I dare to guess that the token was in your case set after the `callFactory` was set on the client, since all the other data is picked up just fine. (SDK user agent headers, preview endpoint)

If that is not the case, do you mind sharing the code you are using?

Greetings,
Mario

**Comment by fcduarte** [comment]
Hi Mario,

you're correct. I was calling it before setting the space and token, my bad. Now that the bearer token is back I still can't see OkHttp setting the If-None-Match header on the subsequent response after a initial successful request. Here's the initialization code:

````
        Builder clientBuilder = CDAClient
            .builder()
            .setSpace(resources.getString(R.string.CDASpaceKey))
            .setToken(resources.getString(R.string.CDAAccessToken));

        if (resources.getBoolean(R.bool.CDAPreviewEnabled)) {
            clientBuilder.preview();
        }

        final OkHttpClient.Builder okBuilder = clientBuilder.defaultCallFactoryBuilder();
        okBuilder.cache(new Cache(context.getCacheDir(), CACHE_SIZE_BYTES));

        clientBuilder.setCallFactory(okBuilder.build());
        client = clientBuilder.build();
````

Could you try to simulate on your end? Thanks!

**Comment by fcduarte** [comment]
Hi Mario,

thanks again for the detailed response. You're totally correct, I was fooled by the response code logged on logcat. Since Contentful does pinning I wasn't able to inspect the response, I didn't know Android Profiler was that powerful! 

I'm closing it now, thanks!
