### ISSUE TITLE
fetchOne not linking

### ISSUE THREAD

**Issue by jameshays** [contentful/contentful.java#59]
I have a model service layer with well defined custom classes.  When I search for an entry with entries().fetchAll(...), I get a well defined object list with linked subentries marshalled as expected.  However, if I use entries().fetchOne(id) I get a well defined object, but the linked subentries are LinkedTreeMaps and I get this error:

java.lang.ClassCastException: com.google.gson.internal.LinkedTreeMap cannot be cast to ...

thoughts?  Am I missing a setting to perform the linking?

EDIT: I'm using version 2.0.1
```
    <dependency>
      <groupId>com.contentful.java</groupId>
      <artifactId>java-sdk</artifactId>
      <version>2.0.1</version>
    </dependency>
```

**Comment by grncdr** [comment]
Hi James,

This is a limitation of the underlying API. When fetching multiple entries (e.g. `GET /spaces/{spaceId}/entries?content_type={contentTypeId}&include=2`) the response is a collection object that contains linked resources under it's `includes` property. However, when fetching an individual entry (e.g. `GET /spaces/{spaceId}/entries/{entryId}`) the response is the entry itself, without any `includes`. This means that the Java library can't stitch together the object references without performing additional requests.

The simplest workaround is to use `fetchAll(ImmutableMap.of("sys.id", id)).getItems().get(0)` instead of `fetchOne(id)` in your model layer (note that `ImmutableMap` comes from Guava, I just used it to keep the example concise). Adding support for `includes` to individual resources may happen in a future version of the API.

**Comment by tomxor** [comment]
In addition, links might not resolve properly due to other reasons (i.e. the linked resource was deleted), so in order to workaround the `ClassCastException` you could optionally use `nullifyUnresolvedLinks()` method of `Client.Builder`, which as the name suggests replaces any unresolved links with null.

**Comment by jameshays** [comment]
Thanks. Does the objective c library have this same issue?  I don't recall running across it, but maybe I need to take another look

**Comment by tomxor** [comment]
Apparently the objc SDK generates this query automatically in case you use it's equivalent of `fetchOne()`, see: https://github.com/contentful/contentful.objc/blob/master/Code/CDAClient.m#L215-L233

Perhaps we could make this the default behaviour for the Java SDK as well.

**Comment by jameshays** [comment]
That sounds great. I will match that in my service layer wrapper as well.

**Comment by jameshays** [comment]
Feel free to close the issue if desired

**Comment by tomxor** [comment]
Current users might rely on testing the status code of the response or even the response body on failures using a `RetrofitError` instance. In case we modify the `fetchOne()` function as discussed above, it will result in completely different behaviour (e.g. when requesting a non-existing resource by ID then an empty array would be returned). This is a fairly simple workaround to implement if desired, I thing it is best to keep things as they are.

**Comment by jameshays** [comment]
That is fine.  Here's what I'm doing
```
    private <T extends CMEntry> T fetch(String identifier) {
        Map<String, String> query = new HashMap<String, String>();
        query.put("sys.id", identifier);
        CDAArray results = client.entries().fetchAll(query);
        CDAResource entry = null;
        if(results != null && results.getItems().size() > 0) {
            entry = results.getItems().get(0);
        }

        //noinspection unchecked
        return (T) entry;
    }
```

And I'll be adding a boolean param to the fetch to indicate whether to use the includes in which case it will either run this code or the code you provide.

**Comment by tomxor** [comment]
@jameshays thanks for sharing!
